### ISSUE TITLE
First Artisan Migrate

### ISSUE THREAD

**Issue by Iwhite67** [daveroverts/bmac#357]
Hello, i make the first Artisan Migrate from last release

![image](https://user-images.githubusercontent.com/9698964/141672202-0b19a6eb-5ca3-4c1c-a92a-15d2f88100cf.png)

this is a problem from my side or migrate side ?

**Comment by daveroverts** [comment]
@Iwhite67 I just created a new branch `feature/email-unique-migration`. Can you check if it works? If it does, I'll merge it in `dev` and `master`
FYI: Right before creating the branch, I created a new database, and did `php artisan migrate:fresh`, no issues with MySQL.

**Comment by Iwhite67** [comment]
i check after

**Comment by Iwhite67** [comment]
so, have test with just php artisan migrate

this is good

**Comment by daveroverts** [comment]
Added in #358
