### ISSUE TITLE
Import data for multi-flights type of event does not work

### ISSUE THREAD

**Issue by bedrich-schindler** [daveroverts/bmac#853]
When we create multi-flights type of event and we want to import data using template, it fails with following error:

![image](https://github.com/daveroverts/bmac/assets/10213870/34d6eebd-ce4a-4bcc-9376-36bdf8a369f7)

Description on Import page looks like:

![image](https://github.com/daveroverts/bmac/assets/10213870/911f647e-c736-422f-9dc4-db956fb5be85)

Excel template looks like:

<img width="521" alt="image" src="https://github.com/daveroverts/bmac/assets/10213870/ed0855e3-7fe6-4cda-a11c-caf6a5e7aa31">

I would fix that be we does not either understand why there are 3 airport fields in `BookingImports:model()`. The fix would be great as we are unable to import data for upcoming event.

**Comment by DarrianCZE** [comment]
Apologies for urging this, but we were not expecting issue of this kind on a globally used software like this. We have an event at the end of this month, for which this booking was intended, so a fast resolution would be extremely appreciated. Many thanks!

**Comment by daveroverts** [comment]
I'll try to give a more detailed answer later tonight. 2 things that could help for now:
- Don't use the 'multi flights' event type. This type was requested for the VATEUD On-Air event, where you can book 2 flights under one booking (example: EHAM-EIDW-LFPG). I never was a big fan of implementing this in the first place. Anyways, do you want this for your event?
- If you really want to use this horrible event type, temporary use [v4.0.0](https://github.com/daveroverts/bmac/releases/tag/v4.0.0)

**Comment by DarrianCZE** [comment]
We were not sure what other event type we should use. We would like a booking for both departures and arrivals from one airport to various airports. Other event types (at least as I understand them) did not fit our requirement.

**Comment by daveroverts** [comment]
It doesn't matter what you choose. From what I can remember, the handling doesn't change, except with 'multi flights'.

Let me describe 2 different use cases:

## Normal events (City-Pair, Fly-In, Groupflight, One way):
One booking = One flight. Examples:
- EHAM - EGLL
- EGLL - EHAM
- LFPG - ENGM

## Multi-Flight:
One booking = Two flights. Examples:
- EHAM - EIDW - LFPG
- LOWW - ENGM - EFHK
- LOWI - EHRD - EKCH

**Comment by DarrianCZE** [comment]
Yes, we have just realized that! Many thanks, it is very appreciated. Also, this could be a note for the future, this system doesn't really have any documentation on how it works, and it could be very beneficial for new users. Especially since the system itself doesn't really tell you how things work in the GUI.
