### ISSUE TITLE
Export data does not work

### ISSUE THREAD

**Issue by bedrich-schindler** [daveroverts/bmac#854]
It may be connected to #853.

When we want to export data from multi-flight event, it fails with following error:

![image](https://github.com/daveroverts/bmac/assets/10213870/1a19de32-1a69-451e-a3ad-0dabb3a57a99)

**Comment by daveroverts** [comment]
Fixed in [v4.1.3](https://github.com/daveroverts/bmac/releases/tag/v4.1.3)
